# -*- coding: utf-8 -*-
"""Extra_Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FvM_ysm6w-qxF7d6s4yZdW4HLMSyodsk

Q1. Write a Python function to find the minimum of five numbers.

Q2. Write a Python function to add all the numbers in a given list.

---


ls = [23, 34, 56, 70, 81, 90]

Q3. Write a Python funciton to reverse a string given by the user.

Q4.  Write a Python function that counts the number of digits, upper case

*   List item
*   List item

letters and lower case letters in the given string : mystr = "riChard@98#ABC"

Q5. Write a Python function to print the prime numbers from a given list: ls = [10,11,12,15]

Q6. Write a Python function to sort the given list in alphabetical order. str_list = ["richard", "namgay", "ramper"]

Q7. Write a Python function to square a number given by user.

Q8. Write a Python function to compute your age for the date of birth given by user.

Q9. Write a Python function to compute y = 3x^2-4x.

Q10. Write a Python function to create an email using a name given by user.
"""