# -*- coding: utf-8 -*-
"""Lambda_Ex_Eaint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CFl-Zzg-_uPsHO-28u3snlETxE3w8kib
"""

now = 2023

age_return = lambda birth_year: now - birth_year

birth_year = int(input("Let me know your birth year - "))

get_age = lambda: age_return(birth_year)

age = get_age()

print(age)

add = lambda cost:cost + cost * 0.10

cost = float(input("What's your cost ?"))

price = add(cost)
print(price)

names = ['Richard', 'Karam', 'Karpo', 'Sonam', 'Ugyen']
domain = 'gmail.com'

for name in names:
    email = name.lower() + '@' + domain
    print(email)

your_email = lambda name, domain: name + "@" + domain

name = str(input("Tell me your name - "))
domain = "gmail.com"

email = your_email(name, domain)
print(email)

old_list = [2, 4, 6, 7, 9]
squared_list = []

for number in old_list:
    squared_list.append(number ** 2)

print(squared_list)